Feature.pwm
chalmers-revere/opendlv.miniature pull request #3
Opened 2017-02-23 21:29 UTC by bjornborg

2017-02-24 22:17 UTC, olbender requested changes
Code is very nice, but some name changes

2017-02-24 22:17 UTC, olbender commented on code/proxy-miniature/gpio/src/Gpio.cpp
> +void Gpio::SetValue(uint16_t const a_pin, bool const val)
Missing "a_"

2017-02-24 22:17 UTC, olbender commented on resources/odvd/ODVDMiniature.odvd
> +  uint32 dutyCycle [id = 2];
Since non-standard unit: dutyCycleNs

2017-02-24 22:17 UTC, olbender commented on resources/odvd/ODVDMiniature.odvd
> +  float value [id = 2];
Change to 'voltage'.

2017-02-24 22:17 UTC, olbender commented on resources/odvd/ODVDMiniature.odvd
> +message opendlv.proxy.DigitalRequest [id = 170] {
Change to: ToggleRequest

2017-02-24 22:17 UTC, olbender commented on resources/odvd/ODVDMiniature.odvd
> +  int32 value [id = 2];
change to:

enum ToggleState {
        Off = 0,
        On = 1
    };
ToggleState state [id = 1];

2017-02-24 22:17 UTC, olbender commented on resources/odvd/ODVDMiniature.odvd
> +message opendlv.proxy.DigitalReading [id = 159] {
Change to ToggleReading

2017-02-24 22:17 UTC, olbender commented on resources/odvd/ODVDMiniature.odvd
> +  int32 value [id = 2];
enum ToggleState {
        Off = 0,
        On = 1
    };
ToggleState state [id = 1];

2017-02-24 22:17 UTC, olbender commented on usecases/latest/host.tme290/configuration
> +proxy-miniature-pwm.dutyCycles = 1500000,1500000
Change to periodsNs and dutyCyclesNs

2017-02-27 13:39 UTC, bjornborg commented
Please, review again.

2017-02-27 13:59 UTC, olbender approved these changes

2017-02-27 13:59 UTC, merged